In [141]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from IndustryMap2 import industry_categories

In [142]:
df = pd.read_csv('../SavedData/dataset2_cleaned.csv')
df['Datetime'] = pd.to_datetime(df['Datetime'])

# Remove capitalization and spaces from 'Third Party Name' column
df['Third Party Name'] = df['Third Party Name'].str.lower().str.replace(' ', '')

In [143]:
training_transactions, testing_transactions = train_test_split(df, test_size=0.2, random_state=2)

## Remove certain industries

In [144]:
training_transactions

Date Timestamp   Account No      Balance  Amount  \
98763   01/06/2023  11:43:00  660561861.0  1069.557925  -12.99   
202021  31/10/2023  23:59:00  229205098.0  8430.205394   -7.00   
9195    08/01/2023  10:59:00  191161970.0  1174.555000  -52.39   
187042  11/10/2023  08:32:00  519933553.0  -354.791496  -18.22   
138671  01/08/2023  09:57:00  762700245.0  1756.224700  -38.97   
...            ...       ...          ...          ...     ...   
175638  30/09/2023  08:26:00  973086490.0  8501.682677  -39.28   
95816   31/05/2023  23:59:00  737645298.0 -1415.637550  -18.99   
203245  01/11/2023  03:41:00  304455868.0  3349.715880  -14.48   
100879  05/06/2023  08:23:00  198630866.0  -222.556324  -61.23   
89256   22/05/2023  09:11:00  706250160.0  4390.333589  -32.13   

        Third Party Account No Third Party Name            Datetime  
98763                      NaN     sportsdirect 2023-06-01 11:43:00  
202021                     NaN             xbox 2023-10-31 23:59:00  
9195                       NaN            tesco 2023-01-08 10:59:00  
187042                     NaN            tesco 2023-10-11 08:32:00  
138671                     NaN     sportsdirect 2023-08-01 09:57:00  
...                        ...              ...                 ...  
175638                     NaN        cooplocal 2023-09-30 08:26:00  
95816                      NaN          puregym 2023-05-31 23:59:00  
203245                     NaN          topshop 2023-11-01 03:41:00  
100879                     NaN            tesco 2023-06-05 08:23:00  
89256                      NaN            tesco 2023-05-22 09:11:00  

[183355 rows x 8 columns]

In [145]:
# Find all keys in the dictionary where the value is 'subscription' or 'finance'
companies_to_remove = [company for company, category in industry_categories.items()
                       if category in ['subscription', 'finance']]
companies_to_remove.append('grandunionbjj')
training_transactions = training_transactions[~((training_transactions['Third Party Name'] == 'amazon') & (training_transactions['Amount'] == -7.99))]
testing_transactions = testing_transactions[~((testing_transactions['Third Party Name'] == 'amazon') & (testing_transactions['Amount'] == -7.99))]

training_transactions = training_transactions[~training_transactions['Third Party Name'].isin(companies_to_remove)]
testing_transactions = testing_transactions[~testing_transactions['Third Party Name'].isin(companies_to_remove)]



In [146]:
testing_transactions[testing_transactions['Third Party Name'] == 'amazon']

Date Timestamp   Account No       Balance  Amount  \
55126   28/03/2023  08:55:00  905860285.0   6720.051838   -9.60   
153121  29/08/2023  19:52:00  414805878.0  11699.926168   -5.89   
208194  08/11/2023  19:19:00  859603181.0   3724.759408   -7.58   
142872  08/08/2023  17:33:00  815993333.0   1462.477842  -37.00   
47910   08/03/2023  17:14:00  522188082.0   5236.474130  -33.84   
...            ...       ...          ...           ...     ...   
183012  04/10/2023  02:52:00  873693307.0  10069.391632   -5.83   
142051  07/08/2023  02:07:00  815385232.0   8250.566744  -42.17   
191146  19/10/2023  04:41:00  305778936.0   9324.831923   -3.50   
209064  10/11/2023  14:52:00  970298834.0   2858.103792  -11.78   
167194  14/09/2023  08:21:00  200080192.0   8785.061272  -20.74   

        Third Party Account No Third Party Name            Datetime  
55126                      NaN           amazon 2023-03-28 08:55:00  
153121                     NaN           amazon 2023-08-29 19:52:00  
208194                     NaN           amazon 2023-11-08 19:19:00  
142872                     NaN           amazon 2023-08-08 17:33:00  
47910                      NaN           amazon 2023-03-08 17:14:00  
...                        ...              ...                 ...  
183012                     NaN           amazon 2023-10-04 02:52:00  
142051                     NaN           amazon 2023-08-07 02:07:00  
191146                     NaN           amazon 2023-10-19 04:41:00  
209064                     NaN           amazon 2023-11-10 14:52:00  
167194                     NaN           amazon 2023-09-14 08:21:00  

[1218 rows x 8 columns]

In [147]:
training_payments_df = training_transactions[training_transactions['Amount'] > 0].copy()
training_expenditures_df = training_transactions[training_transactions['Amount'] < 0].copy()
training_expenditures_df["Amount"] = training_expenditures_df["Amount"].abs()

testing_payments_df = testing_transactions[testing_transactions['Amount'] > 0].copy()
testing_expenditures_df = testing_transactions[testing_transactions['Amount'] < 0].copy()
testing_expenditures_df["Amount"] = testing_expenditures_df["Amount"].abs()

In [148]:
training_expenditures_df = training_expenditures_df.copy()
testing_expenditures_df = testing_expenditures_df.copy()

training_expenditures_df['DayOfWeek'] = training_expenditures_df['Datetime'].dt.dayofweek
training_expenditures_df['DayOfMonth'] = training_expenditures_df['Datetime'].dt.day
training_expenditures_df['MonthOfYear'] = training_expenditures_df['Datetime'].dt.month

testing_expenditures_df['DayOfWeek'] = testing_expenditures_df['Datetime'].dt.dayofweek
testing_expenditures_df['DayOfMonth'] = testing_expenditures_df['Datetime'].dt.day
testing_expenditures_df['MonthOfYear'] = testing_expenditures_df['Datetime'].dt.month

In [149]:
training_expenditures_df = training_expenditures_df.copy()
testing_expenditures_df = testing_expenditures_df.copy()

training_expenditures_df['Hour'] = training_expenditures_df['Datetime'].dt.hour
testing_expenditures_df['Hour'] = testing_expenditures_df['Datetime'].dt.hour

In [150]:
patterns_train = training_expenditures_df.groupby(['Account No', 'Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Third Party Name'])['Amount'].sum().reset_index()
patterns_test = testing_expenditures_df.groupby(['Account No', 'Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Third Party Name'])['Amount'].sum().reset_index()

In [151]:
account_no = list(df['Account No'].unique())
key_list = account_no
value_list = [0] * len(account_no)
account_num_models = dict(zip(key_list, value_list))

In [152]:
for account in account_no:
    X_train = patterns_train[patterns_train['Account No'] == account][['Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Amount']]
    X_test = patterns_test[patterns_test['Account No'] == account][['Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Amount']]
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    user_model = IsolationForest(n_estimators=100, contamination=0.01)
    account_num_models[account] = user_model.fit(X_train_scaled)
    
    predictions = account_num_models[account].predict(X_test_scaled)
    
    # Save predictions to the DataFrame
    patterns_test.loc[X_test.index, 'Prediction'] = predictions
    
# Check the DataFrame to see the predictions column
print(patterns_test.head())

    Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear Third Party Name  \
0  101531259.0     8          0          19            6            tesco   
1  101531259.0     8          2          11           10            tesco   
2  101531259.0     8          5          12            8            tesco   
3  101531259.0     9          3          30           11    fivesensesart   
4  101531259.0     9          5          30            9     sportsdirect   

   Amount  Prediction  
0  161.08         1.0  
1   65.20         1.0  
2   95.92         1.0  
3    7.49         1.0  
4   30.99         1.0  


In [153]:
patterns_test[patterns_test['Prediction'] == -1].head(60)

Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear Third Party Name  \
25    105375973.0     1          6          29            1   sainsburylocal   
184   108563213.0    10          6           2            7          matalan   
272   108931112.0    20          2           1            2            tesco   
395   116598243.0     1          0          30           10        deliveroo   
627   119943495.0    10          6           1            1      blackwell's   
657   120634201.0     3          6           3           12          justeat   
666   120634201.0     7          6           3           12          revella   
716   120634201.0    20          2           1            2            tesco   
757   122884111.0     5          0           1            5        deliveroo   
820   124102251.0    15          6           3           12          revella   
863   124377686.0     3          5          27            5        deliveroo   
966   128033695.0    10          0          16            1      gamestation   
975   128033695.0    14          1           8            8          matalan   
1103  131388684.0    11          6           5           11          topshop   
1128  131388684.0    17          4          28            7          fatface   
1183  133755851.0    16          0          30           10          topshop   
1206  134847904.0     9          0          31            7            tesco   
1228  134847904.0    20          1          31            1            tesco   
1267  137822385.0     1          0           4            9            boots   
1405  140893085.0    19          0          20            2            tesco   
1482  143003091.0    13          5          28            1     sportsdirect   
1484  143003091.0    17          6          29            1        cooplocal   
1539  143383029.0    19          0          26            6          justeat   
1646  145387690.0    15          6          19           11          revella   
1748  146909202.0    17          4           1           12     sportsdirect   
1847  149684419.0    17          6           1           10          revella   
1858  151278285.0     2          4          10            3        deliveroo   
1868  151278285.0    16          4           1           12     sportsdirect   
1890  151916463.0    14          0           2           10          matalan   
1962  151968462.0    16          6          23            4          topshop   
2044  154246234.0    10          0           3            7          topshop   
2056  155317149.0     4          2           1            3          justeat   
2119  155867488.0    18          0           4           12       hobbylobby   
2228  162370388.0    13          0          23            1            tesco   
2231  162370388.0    13          6          28            5            tesco   
2381  166019891.0     2          0           4           12          matalan   
2405  166019891.0    12          5           6            5          fatface   
2570  169006407.0    20          0           6            3            tesco   
2686  170637730.0    13          0          22            5          fatface   
2693  170637730.0    16          0           6           11          topshop   
2723  172084472.0    20          2           1            2          justeat   
2843  176922958.0    19          5           2           12            tesco   
2911  179173981.0    22          0           2            1         thecrown   
2951  180616589.0    17          4          24            3          matalan   
2995  183186021.0    20          0           2            1            tesco   
3050  183888402.0    19          0           2            1            tesco   
3119  187111705.0    11          6          29            1   sainsburylocal   
3120  187111705.0    12          0           4            9          topshop   
3237  187541224.0    22          6           3           12          fatface   
3290  1

In [120]:
patterns_test[patterns_test['Account No'] == 108563213.0]

Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear Third Party Name  \
136  108563213.0     0          6           1            1           amazon   
137  108563213.0     2          0          28            8          fatface   
138  108563213.0     3          0           4            9        cooplocal   
139  108563213.0     3          2          18           10        cooplocal   
140  108563213.0     3          3          16           11             etsy   
..           ...   ...        ...         ...          ...              ...   
205  108563213.0    19          1          31            1            tesco   
206  108563213.0    23          1          28            2           amazon   
207  108563213.0    23          1          31           10           amazon   
208  108563213.0    23          2          31            5           amazon   
209  108563213.0    23          4          31            3           amazon   

     Amount  Prediction  
136    7.99        -1.0  
137   47.83         1.0  
138   48.75         1.0  
139   44.90         1.0  
140   30.34         1.0  
..      ...         ...  
205   64.36        -1.0  
206    7.99         1.0  
207    7.99         1.0  
208    7.99         1.0  
209    7.99         1.0  

[74 rows x 8 columns]

In [105]:
import matplotlib.pyplot as plt

account = 678330503.0

# Predict on the test dataset
predictions = account_num_models[account].predict(X_test_scaled)

print(X_test_scaled)
print(predictions)

# Analyze predictions
#n_outliers = (predictions == -1).sum()
#n_inliers = (predictions == 1).sum()

#print(f"Number of outliers detected: {n_outliers}")
#print(f"Number of inliers detected: {n_inliers}")

# Plot results (if feasible)
#plt.figure(figsize=(10, 6))
#plt.scatter(X_test_scaled[:, 0], X_test_scaled[:, 1], c=predictions, cmap='coolwarm', edgecolor='k', s=50)
#plt.title('Isolation Forest Outlier Detection')
#plt.xlabel('Feature 1')
#plt.ylabel('Feature 2')
#plt.show()

[[-2.61259834 -1.05018253  0.05450421 -0.09401777 -0.97974706]
 [-2.10484955  0.46318094  0.49861256  1.38340428 -0.88579437]
 [-1.59710075 -1.05018253 -0.50063123  0.49695105 -0.08033482]
 [-1.59710075 -1.05018253  0.05450421 -0.09401777 -0.25398895]
 [-1.08935196 -1.05018253 -0.61165832 -1.27595541  0.27383513]
 [-0.58160316 -1.05018253 -1.16679376  1.08791987 -0.99109527]
 [-0.58160316 -1.05018253  0.38758547  1.08791987  0.11390444]
 [-0.07385437 -0.54572804  1.053748    1.38340428  0.75151592]
 [ 0.43389442 -0.04127355 -0.38960415  1.38340428 -1.09560444]
 [ 0.43389442 -0.04127355  0.05450421 -0.980471    0.80403442]
 [ 0.43389442 -0.04127355  0.38758547  1.38340428  0.69926134]
 [ 0.43389442  0.96763543 -0.50063123 -0.980471   -1.17477805]
 [ 0.43389442  0.96763543  1.71991053  0.20146664 -0.34371904]
 [ 0.43389442  1.47208992  0.38758547 -0.980471   -0.35770638]
 [ 0.43389442  1.47208992  1.053748    0.20146664  0.17170117]
 [ 0.43389442  1.47208992  1.38682926 -0.09401777  0.91