In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

In [90]:
df = pd.read_csv('../SavedData/dataset2_cleaned.csv')
df['Datetime'] = pd.to_datetime(df['Datetime'])

In [91]:
training_transactions, testing_transactions = train_test_split(df, test_size=0.2, random_state=2)

In [92]:
training_payments_df = training_transactions[training_transactions['Amount'] > 0].copy()
training_expenditures_df = training_transactions[training_transactions['Amount'] < 0].copy()
training_expenditures_df["Amount"] = training_expenditures_df["Amount"].abs()

testing_payments_df = testing_transactions[testing_transactions['Amount'] > 0].copy()
testing_expenditures_df = testing_transactions[testing_transactions['Amount'] < 0].copy()
testing_expenditures_df["Amount"] = testing_expenditures_df["Amount"].abs()

In [93]:
training_expenditures_df = training_expenditures_df.copy()
testing_expenditures_df = testing_expenditures_df.copy()

training_expenditures_df['DayOfWeek'] = training_expenditures_df['Datetime'].dt.dayofweek
training_expenditures_df['DayOfMonth'] = training_expenditures_df['Datetime'].dt.day
training_expenditures_df['MonthOfYear'] = training_expenditures_df['Datetime'].dt.month

testing_expenditures_df['DayOfWeek'] = testing_expenditures_df['Datetime'].dt.dayofweek
testing_expenditures_df['DayOfMonth'] = testing_expenditures_df['Datetime'].dt.day
testing_expenditures_df['MonthOfYear'] = testing_expenditures_df['Datetime'].dt.month

In [94]:
training_expenditures_df = training_expenditures_df.copy()
testing_expenditures_df = testing_expenditures_df.copy()

training_expenditures_df['Hour'] = training_expenditures_df['Datetime'].dt.hour
testing_expenditures_df['Hour'] = testing_expenditures_df['Datetime'].dt.hour

In [95]:
patterns_train = training_expenditures_df.groupby(['Account No', 'Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Datetime'])['Amount'].sum().reset_index()
patterns_test = testing_expenditures_df.groupby(['Account No', 'Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Datetime'])['Amount'].sum().reset_index()

In [96]:
account_no = list(df['Account No'].unique())
key_list = Account_Nos
value_list = [0] * len(Account_Nos)
account_num_models = dict(zip(key_list, value_list))

In [122]:
for account in account_no:
    X_train = patterns_train[patterns_train['Account No'] == account][['Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Amount']]
    X_test = patterns_test[patterns_test['Account No'] == account][['Hour', 'DayOfWeek', 'DayOfMonth', 'MonthOfYear', 'Amount']]
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    user_model = IsolationForest(n_estimators=100, contamination=0.05)
    account_num_models[account] = user_model.fit(X_train_scaled)
    
    predictions = account_num_models[account].predict(X_test_scaled)
    
    # Save predictions to the DataFrame
    patterns_test.loc[X_test.index, 'Prediction'] = predictions
    
# Check the DataFrame to see the predictions column
print(patterns_test.head())

    Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear            Datetime  \
0  101531259.0     0          2           1            2 2023-02-01 00:00:00   
1  101531259.0     0          4           1            9 2023-09-01 00:00:00   
2  101531259.0     0          4           1           12 2023-12-01 00:00:00   
3  101531259.0     0          5           1            4 2023-04-01 00:00:00   
4  101531259.0     8          0          19            6 2023-06-19 08:37:00   

   Amount  Prediction  
0  859.00        -1.0  
1  859.00         1.0  
2  859.00        -1.0  
3  859.00        -1.0  
4  161.08         1.0  


In [123]:
patterns_test.head(50)

Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear            Datetime  \
0   101531259.0     0          2           1            2 2023-02-01 00:00:00   
1   101531259.0     0          4           1            9 2023-09-01 00:00:00   
2   101531259.0     0          4           1           12 2023-12-01 00:00:00   
3   101531259.0     0          5           1            4 2023-04-01 00:00:00   
4   101531259.0     8          0          19            6 2023-06-19 08:37:00   
5   101531259.0     8          2          11           10 2023-10-11 08:21:00   
6   101531259.0     8          5          12            8 2023-08-12 08:29:00   
7   101531259.0     9          3          30           11 2023-11-30 09:21:00   
8   101531259.0     9          3          31            8 2023-08-31 09:41:00   
9   101531259.0     9          5          30            9 2023-09-30 09:26:00   
10  101531259.0     9          6           1            1 2023-01-01 09:37:00   
11  101531259.0     9          6           3           12 2023-12-03 09:26:00   
12  101531259.0    10          1          28            2 2023-02-28 10:09:00   
13  101531259.0    12          0           5            6 2023-06-05 12:29:00   
14  101531259.0    12          0           5            6 2023-06-05 12:57:00   
15  101531259.0    13          0           6            2 2023-02-06 13:01:00   
16  101531259.0    13          0          12            6 2023-06-12 13:09:00   
17  101531259.0    16          6           1            1 2023-01-01 16:52:00   
18  101531259.0    21          2           8            3 2023-03-08 21:07:00   
19  101531259.0    23          0          31            7 2023-07-31 23:59:00   
20  101531259.0    23          1          31            1 2023-01-31 23:59:00   
21  101531259.0    23          2          31            5 2023-05-31 23:59:00   
22  101531259.0    23          5          30            9 2023-09-30 23:59:00   
23  104832000.0     0          2           1            2 2023-02-01 00:00:00   
24  104832000.0     0          2           1           11 2023-11-01 00:00:00   
25  104832000.0     0          6           1            1 2023-01-01 00:00:00   
26  104832000.0     0          6           1           10 2023-10-01 00:00:00   
27  104832000.0     9          5          21            1 2023-01-21 09:31:00   
28  104832000.0    10          6          12            2 2023-02-12 10:44:00   
29  104832000.0    12          6           9            7 2023-07-09 12:41:00   
30  104832000.0    12          6          28            5 2023-05-28 12:52:00   
31  104832000.0    13          5          21            1 2023-01-21 13:53:00   
32  104832000.0    13          6           1            1 2023-01-01 13:47:00   
33  104832000.0    16          0          23            1 2023-01-23 16:36:00   
34  104832000.0    16          4           3           11 2023-11-03 16:50:00   
35  104832000.0    17          0          27            3 2023-03-27 17:40:00   
36  104832000.0    17          2          15            2 2023-02-15 17:16:00   
37  104832000.0    17          2          15            2 2023-02-15 17:44:00   
38  104832000.0    18          0          19            6 2023-06-19 18:19:00   
39  104832000.0    23          0          31            7 2023-07-31 23:59:00   
40  104832000.0    23          1          28            2 2023-02-28 23:59:00   
41  104832000.0    23          1          31           10 2023-10-31 23:59:00   
42  104832000.0    23          3          30           11 2023-11-30 23:59:00   
43  104832000.0    23          3          31            8 2023-08-31 23:59:00   
44  104832000.0    23          4          30            6 2023-06-30 23:59:00   
45  104832000.0    23          4          31            3 2023-03-31 23:59:00   
46  104832000.0    23          5          30            9 2023-09-30 23:59:00   
47  104832000.0    23          6          30            4 2023-04-30 23:59:00   
48  105375973.0     1          6    

In [124]:
patterns_test[patterns_test['Account No'] == 108563213.0].head(60)

Account No  Hour  DayOfWeek  DayOfMonth  MonthOfYear  \
172  108563213.0     0          6           1            1   
173  108563213.0     2          0          28            8   
174  108563213.0     3          0           4            9   
175  108563213.0     3          2          18           10   
176  108563213.0     3          3          16           11   
177  108563213.0     4          1           5           12   
178  108563213.0     4          1          25            4   
179  108563213.0     4          2           5            7   
180  108563213.0     4          3           3            8   
181  108563213.0     4          4           2            6   
182  108563213.0     4          5           5            8   
183  108563213.0     4          5           9            9   
184  108563213.0     4          5          22            4   
185  108563213.0     5          3          26           10   
186  108563213.0     5          4           1           12   
187  108563213.0     5          4          21            7   
188  108563213.0     5          5          12            8   
189  108563213.0     6          0           2           10   
190  108563213.0     6          0          12            6   
191  108563213.0     6          0          26            6   
192  108563213.0     6          1          10           10   
193  108563213.0     6          2          27            9   
194  108563213.0     6          5          21           10   
195  108563213.0     6          6           8           10   
196  108563213.0     7          0          13           11   
197  108563213.0     7          0          20           11   
198  108563213.0     7          1           8            8   
199  108563213.0     7          2           6            9   
200  108563213.0     7          2          14            6   
201  108563213.0     7          2          19            7   
202  108563213.0     7          2          30            8   
203  108563213.0     7          3           6            7   
204  108563213.0     7          3          10            8   
205  108563213.0     7          4           8            9   
206  108563213.0     7          6          22           10   
207  108563213.0     8          2          21            6   
208  108563213.0     8          2          29           11   
209  108563213.0     8          2          29           11   
210  108563213.0     8          3          28            9   
211  108563213.0     8          4          10            2   
212  108563213.0     8          6          25            6   
213  108563213.0     9          0          31            7   
214  108563213.0     9          3          23            3   
215  108563213.0     9          5           2            9   
216  108563213.0     9          5           4            3   
217  108563213.0     9          5           8            4   
218  108563213.0     9          5          15            4   
219  108563213.0    10          5          11           11   
220  108563213.0    10          5          24            6   
221  108563213.0    10          5          28           10   
222  108563213.0    10          6           2            7   
223  108563213.0    10          6           2            7   
224  108563213.0    10          6          23            7   
225  108563213.0    11          5          11           11   
226  108563213.0    12          5          25            3   
227  108563213.0    12          6           5            2   
228  108563213.0    13          5           8            7   
229  108563213.0    13          6           4            6   
230  108563213.0    14          6           2            7   
231  108563213.0    16          5          11           11   

               Datetime  Amount  Prediction  
172 2023-01-01 00:00:00    7.99        -1.0  
173 2023-08-28 02:42:00   47.83         1.0  
174 2023-09-04 03:52:00   48.75         1.0  
175 2023-10-18 03:54:00   44.90        

In [105]:
import matplotlib.pyplot as plt

account = 678330503.0

# Predict on the test dataset
predictions = account_num_models[account].predict(X_test_scaled)

print(X_test_scaled)
print(predictions)

# Analyze predictions
#n_outliers = (predictions == -1).sum()
#n_inliers = (predictions == 1).sum()

#print(f"Number of outliers detected: {n_outliers}")
#print(f"Number of inliers detected: {n_inliers}")

# Plot results (if feasible)
#plt.figure(figsize=(10, 6))
#plt.scatter(X_test_scaled[:, 0], X_test_scaled[:, 1], c=predictions, cmap='coolwarm', edgecolor='k', s=50)
#plt.title('Isolation Forest Outlier Detection')
#plt.xlabel('Feature 1')
#plt.ylabel('Feature 2')
#plt.show()

[[-2.61259834 -1.05018253  0.05450421 -0.09401777 -0.97974706]
 [-2.10484955  0.46318094  0.49861256  1.38340428 -0.88579437]
 [-1.59710075 -1.05018253 -0.50063123  0.49695105 -0.08033482]
 [-1.59710075 -1.05018253  0.05450421 -0.09401777 -0.25398895]
 [-1.08935196 -1.05018253 -0.61165832 -1.27595541  0.27383513]
 [-0.58160316 -1.05018253 -1.16679376  1.08791987 -0.99109527]
 [-0.58160316 -1.05018253  0.38758547  1.08791987  0.11390444]
 [-0.07385437 -0.54572804  1.053748    1.38340428  0.75151592]
 [ 0.43389442 -0.04127355 -0.38960415  1.38340428 -1.09560444]
 [ 0.43389442 -0.04127355  0.05450421 -0.980471    0.80403442]
 [ 0.43389442 -0.04127355  0.38758547  1.38340428  0.69926134]
 [ 0.43389442  0.96763543 -0.50063123 -0.980471   -1.17477805]
 [ 0.43389442  0.96763543  1.71991053  0.20146664 -0.34371904]
 [ 0.43389442  1.47208992  0.38758547 -0.980471   -0.35770638]
 [ 0.43389442  1.47208992  1.053748    0.20146664  0.17170117]
 [ 0.43389442  1.47208992  1.38682926 -0.09401777  0.91